module.exports = {
	Localization: require('./localization'),
	Utils: require('./utils'),
	Storage: require('./storage'),
	Uploader: require('./uploader'),
	Member: require('./member'),
	Receiver: require('./receiver'),
	Message: require('./message'),
	Middleware: require('./middleware'),
	Permission: require('./permission'),
	Role: require('./role'),
	Database: require('./database'),
	Mailer: require('./mailer'),
	Passport: require('./passport'),
};
